CREATE TABLE IF NOT EXISTS users
(
    id       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    varchar NOT NULL,
    login    varchar NOT NULL,
    name     varchar,
    birthday date    NOT NULL
);

CREATE TABLE IF NOT EXISTS user_friends
(
    user_id     bigint REFERENCES users,
    friend_id   bigint REFERENCES users,
    is_accepted bool NOT NULL DEFAULT false,
    PRIMARY KEY (user_id, friend_id)
);

CREATE TABLE IF NOT EXISTS mpa_ratings
(
    id   integer PRIMARY KEY,
    name varchar NOT NULL
);

CREATE TABLE IF NOT EXISTS films
(
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          varchar NOT NULL,
    description   text,
    release_date  date    NOT NULL,
    duration      integer NOT NULL,
    mpa_rating_id integer REFERENCES mpa_ratings
);

CREATE TABLE IF NOT EXISTS genres
(
    id   integer PRIMARY KEY,
    name varchar NOT NULL
);

CREATE TABLE IF NOT EXISTS film_genres
(
    film_id  bigint REFERENCES films,
    genre_id integer REFERENCES genres,
    PRIMARY KEY (film_id, genre_id)
);

CREATE TABLE IF NOT EXISTS film_likes
(
    user_id bigint REFERENCES users,
    film_id bigint REFERENCES films,
    PRIMARY KEY (user_id, film_id)
);

CREATE TABLE IF NOT EXISTS reviews
(
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content     VARCHAR(1000) NOT NULL,
    is_positive BOOLEAN       NOT NULL,
    user_id     BIGINT        NOT NULL,
    film_id     BIGINT        NOT NULL,
    useful      INT DEFAULT 0,
    CONSTRAINT unique_user_review UNIQUE (user_id, film_id)
);

CREATE TABLE IF NOT EXISTS review_likes
(
    review_id BIGINT  NOT NULL REFERENCES reviews (id) ON DELETE CASCADE,
    user_id   BIGINT  NOT NULL,
    is_like   BOOLEAN NOT NULL,
    PRIMARY KEY (review_id, user_id),
    CONSTRAINT unique_user_review_like UNIQUE (review_id, user_id)
);
