CREATE TABLE IF NOT EXISTS users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email varchar NOT NULL,
  login varchar NOT NULL,
  name varchar,
  birthday date NOT NULL
);

CREATE TABLE IF NOT EXISTS user_friends (
  user_id bigint REFERENCES users ON DELETE CASCADE,
  friend_id bigint REFERENCES users ON DELETE CASCADE,
  is_accepted bool NOT NULL DEFAULT false,
  PRIMARY KEY (user_id, friend_id)
);

CREATE TABLE IF NOT EXISTS mpa_ratings (
  id integer PRIMARY KEY,
  name varchar NOT NULL
);

CREATE TABLE IF NOT EXISTS films (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar NOT NULL,
  description text,
  release_date date NOT NULL,
  duration integer NOT NULL,
  mpa_rating_id integer REFERENCES mpa_ratings
);

CREATE TABLE IF NOT EXISTS genres (
  id integer PRIMARY KEY,
  name varchar NOT NULL
);

CREATE TABLE IF NOT EXISTS directors (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar NOT NULL
);

CREATE TABLE IF NOT EXISTS film_genres (
  film_id bigint REFERENCES films ON DELETE CASCADE,
  genre_id integer REFERENCES genres,
  PRIMARY KEY (film_id, genre_id)
);

CREATE TABLE IF NOT EXISTS film_likes (
  user_id bigint REFERENCES users ON DELETE CASCADE,
  film_id bigint REFERENCES films ON DELETE CASCADE,
  PRIMARY KEY (user_id, film_id)
);

CREATE TABLE IF NOT EXISTS film_directors (
  film_id bigint REFERENCES films ON DELETE CASCADE,
  director_id integer REFERENCES directors,
  PRIMARY KEY (film_id, director_id)
);